### ISSUE TITLE
Resolve issues observed in side-by-side runs

### ISSUE THREAD

**Issue by rsdunlapiv** [esmf-org/noahmp#1] opened 2022-09-08 19:48 UTC

**Comment by uturuncoglu** [comment] 2022-09-14 17:58
The issue is fixed after fixing logical error about ordering the initialization of the states. I am plaining to make more test to be sure and finalize the cap after testing datm configurations. The initial plots of latent and sensible heat fluxes from beginning  and end of 5-day long simulation can be seen in the attached plots.

[plot_cubed_diff_lhtfl_evap_22-03-2021_06:12.pdf](https://github.com/esmf-org/noahmp/files/9568753/plot_cubed_diff_lhtfl_evap_22-03-2021_06.12.pdf)
[plot_cubed_diff_lhtfl_evap_27-03-2021_06:00.pdf](https://github.com/esmf-org/noahmp/files/9568755/plot_cubed_diff_lhtfl_evap_27-03-2021_06.00.pdf)
[plot_cubed_diff_shtfl_hflx_22-03-2021_06:12.pdf](https://github.com/esmf-org/noahmp/files/9568757/plot_cubed_diff_shtfl_hflx_22-03-2021_06.12.pdf)
[plot_cubed_diff_shtfl_hflx_27-03-2021_06:00.pdf](https://github.com/esmf-org/noahmp/files/9568758/plot_cubed_diff_shtfl_hflx_27-03-2021_06.00.pdf)
[plot_cubed_ts_lhtfl_evap.pdf](https://github.com/esmf-org/noahmp/files/9568754/plot_cubed_ts_lhtfl_evap.pdf)
[plot_cubed_ts_shtfl_hflx.pdf](https://github.com/esmf-org/noahmp/files/9568756/plot_cubed_ts_shtfl_hflx.pdf)

**Comment by uturuncoglu** [comment] 2022-09-23 16:30
We have still issue when we update the UFS Weather model. The working version is based on

```
commit 492855ab08f3467eced089a183cd91a2910bb1e3
Author: Dusan Jovic <48258889+DusanJovic-NOAA@users.noreply.github.com>
Date:   Fri Jul 29 11:02:41 2022 -0400
``` 

but when I update the UFS model code to the following commit,

```
commit b5acabf0a6a283e8aa9a2226f30b7aa6922fd198 (origin/develop, origin/HEAD)
Author: Gillian Petro <96886803+gspetro-NOAA@users.noreply.github.com>
Date:   Fri Sep 16 11:34:56 2022 -0400
```

we have large difference when it is compared with the CCPP/noahmp. The spatial bias for latent heat can be seen in plots that are created from simulations done by old and new version of the code.

[new_version.pdf](https://github.com/esmf-org/noahmp/files/9635461/new_version.pdf)
[old_version.pdf](https://github.com/esmf-org/noahmp/files/9635460/old_version.pdf)

**Comment by uturuncoglu** [comment] 2022-09-23 16:35
I also checked every field that goes to noahmpdrv just before calling driver by activating aux debugging in CCPP side and compare them with the values  coming from external noahmp component and they all looks fine. There are small differences but those are also similar in the working copy of the UFS model. So, they could not be the source of the issue.

**Comment by uturuncoglu** [comment] 2022-09-27 15:33
This is fixed by adding gpvs() call and also fixing other couple of issues for the initialization.

**Closed as completed by uturuncoglu** 2022-09-27 15:33 UTC
